using UnityEditor.SearchService;
using UnityEngine;
using UnityEngine.SceneManagement;

public class MapTransfer : MonoBehaviour
{
    [SerializeField] private string targetSceneName; // è¦åˆ‡æ›åˆ°çš„å ´æ™¯åç¨±
    public GameObject handler;
    private void Start()
    {
        Debug.Log("âœ… MapTransfer.cs å•Ÿå‹•æˆåŠŸï¼");
    }
    private void OnTriggerEnter2D(Collider2D other)
    {
        Debug.Log("âš ï¸ é€²å…¥è§¸ç™¼å™¨çš„æ˜¯ï¼š" + other.name);
        Debug.Log("ğŸ” å®ƒçš„ Tag æ˜¯ï¼š" + other.tag); // â† é‡é»åœ¨é€™è¡Œï¼

        if (other.CompareTag("Player"))
        {
            Debug.Log("âœ… Player è§¸ç™¼æˆåŠŸï¼");
            // SceneManager.LoadScene(targetSceneName);
            handler = GameObject.FindGameObjectWithTag("scenehandler");
            handler.GetComponent<LoadingScene>().LoadScene(3);
        }

    }
}
